### ISSUE TITLE
Database could not be found

### ISSUE THREAD

**Issue by friendlymaninthisworld** [Asgarrrr/Luna#16]
user@user-HP-EliteBook-8460p:~/Downloads/Luna-master$ node Luna.js
/home/user/Downloads/Luna-master/node_modules/better-sqlite3/lib/database.js:32
                throw new TypeError('Cannot open database because the directory does not exist');
                ^

TypeError: Cannot open database because the directory does not exist
    at Database (/home/user/Downloads/Luna-master/node_modules/better-sqlite3/lib/database.js:32:9)
    at Object.<anonymous> (/home/user/Downloads/Luna-master/resources/DBInit.js:2:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at new Luna (/home/user/Downloads/Luna-master/Structures/Luna.js:35:26)
    at Object.<anonymous> (/home/user/Downloads/Luna-master/Luna.js:16:16)

**Comment by Asgarrrr** [comment]
Good evening, sorry for the inconvenience, Create a folder "Database" and the problem will be solved.

**Comment by friendlymaninthisworld** [comment]
> Good evening, sorry for the inconvenience, Create a folder "Database" and the problem will be solved.

Wow, that was fast! It worked, thanks.
Do you have a discord or any other group for the bot people could join?
