### ISSUE TITLE
TypeError: collected.first is not a function

### ISSUE THREAD

**Issue by friendlymaninthisworld** [Asgarrrr/Luna#19]
TypeError: collected.first is not a function
    at Play.search (/home/user/Documents/Luna-master/Commands/Music/play.js:232:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Play.handleQuery (/home/user/Documents/Luna-master/Commands/Music/play.js:113:9)
    at async Play.run (/home/user/Documents/Luna-master/Commands/Music/play.js:52:9)

**Comment by Asgarrrr** [comment]
I found the problem, it's when you enter "exit", I'll fix it soon.
