### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined, TypeError: Cannot read property 'end' of null

### ISSUE THREAD

**Issue by friendlymaninthisworld** [Asgarrrr/Luna#20]
TypeError: Cannot read property 'id' of undefined
    at Play.search (/home/user/Documents/Luna-master/Commands/Music/play.js:235:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Play.handleQuery (/home/user/Documents/Luna-master/Commands/Music/play.js:113:9)
    at async Play.run (/home/user/Documents/Luna-master/Commands/Music/play.js:52:9)

TypeError: Cannot read property 'end' of null
    at Skip.run (/home/user/Documents/Luna-master/Commands/Music/skip.js:36:28)
    at Message.run (/home/user/Documents/Luna-master/Events/message.js:97:17)
    at Luna.<anonymous> (/home/user/Documents/Luna-master/Structures/Luna.js:101:60)
    at Luna.emit (node:events:390:22)
    at MessageCreateAction.handle (/home/user/Documents/Luna-master/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)

**Comment by Asgarrrr** [comment]
Hello ! Can you give me more details on how this error happened? the complete command ?

**Comment by Asgarrrr** [comment]
I found the problem, it's when you enter "exit", I'll fix it soon.

**Comment by friendlymaninthisworld** [comment]
Oh i didn't know you commented lol. but it seems like you got it under control

**Comment by Asgarrrr** [comment]
Sorry for all his errors ;(

**Comment by Asgarrrr** [comment]
Normally the problem is solved ! ;3

**Comment by friendlymaninthisworld** [comment]
Lol don't worry, I honestly feel worse for bothering you with the errors. (Maybe it's because I'm Canadian) 
Whatever, I love working on stuff like this. So, thanks for @Asgarrrr.

**Comment by Asgarrrr** [comment]
And I am French, I am a baguette x) And I feel bad to propose something with mistakes :( Sorry
