### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by paolosasso** [Asgarrrr/Luna#40]
Error: Could not load font to the system's font host
    at Object.registerFont (c:\Users\Paolo\Desktop\Luna-master\node_modules\canvas\index.js:48:17)
    at Object.<anonymous> (c:\Users\Paolo\Desktop\Luna-master\Commands\Fun\Levels\rank.js:30:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Luna.loadCommands (c:\Users\Paolo\Desktop\Luna-master\Structures\Luna.js:173:32)
    at Luna.start (c:\Users\Paolo\Desktop\Luna-master\Structures\Luna.js:202:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by xSvxnn** [comment]
how do i fix this
