### ISSUE TITLE
Could load system's font host

### ISSUE THREAD

**Issue by xSvxnn** [Asgarrrr/Luna#41]
Error: Could not load font to the system's font host
    at Object.registerFont (C:\Users\Svenn\Desktop\New folder\Luna\node_modules\canvas\index.js:48:17)
    at Object.<anonymous> (C:\Users\Svenn\Desktop\New folder\Luna\Commands\Fun\Levels\rank.js:30:45)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Luna.loadCommands (C:\Users\Svenn\Desktop\New folder\Luna\Structures\Luna.js:173:32)
    at Luna.start (C:\Users\Svenn\Desktop\New folder\Luna\Structures\Luna.js:202:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

How do i fix this

**Comment by hanonymus90** [comment]
I got the same problem
