### ISSUE TITLE
Button and Music Bug

### ISSUE THREAD

**Issue by rodrigoricky** [Asgarrrr/Luna#46]
For play.js

TypeError: actions.components[2].setEmoji is not a function
    at Play.embedPlayer (C:\Users\User\Desktop\Opal\Commands\Music\play.js:668:35)
    at Play.run (C:\Users\User\Desktop\Opal\Commands\Music\play.js:93:24)

For help.js

TypeError: button.defer is not a function
    at ButtonCollector.<anonymous> (C:\Users\User\Desktop\Opal\Commands\General\help.js:164:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by StandartCoder** [comment]
For help.js

Do button.reply.defer

**Comment by StandartCoder** [comment]
For play.js 

Replace components with Components
