### ISSUE TITLE
Can Not find module

### ISSUE THREAD

**Issue by RomanMule72** [Asgarrrr/Luna#7]
I keep getting this error

```
internal/modules/cjs/loader.js:968
  throw err;

Error: Cannot find module 'C:\Users\minec\Desktop\Luna-master\luna.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

**Comment by friendlymaninthisworld** [comment]
> Hello !
> 
> Luna is in the **src** file, you must be inside it to execute the commands `npm i` and `node luna.js`.

okay, dude I think you need to change either the guide or the actual name of the file. 
the file is "Luna" not "luna"

**Comment by Asgarrrr** [comment]
Mhh indeed, I believe that a cleaning is necessary!  Thanks
